db:
  image: postgres:9.4.5

memcached:
  image: memcached:1.4.27-alpine

redis:
  image: redis:3.2.1-alpine

test:
  image: russianpulse/mazavr-engine
  links:
    - db
    - memcached
    - redis
  environment:
    - RAILS_ENV=test
  env_file:
    - .env.test
  command:
    bundle exec rake db:create db:migrate spec
